/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.adivinhe_o_numero;

import javax.swing.JOptionPane;

/**
 *
 * @author Wanderson
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    Processamento pro = new Processamento();
    int aleatorio, resposta, acerto, erro, tentativa, rodada;
    boolean vazio;

    public FramePrincipal() {
        initComponents();
        iniciar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFdigiteUmNumero = new javax.swing.JTextField();
        JLdigiteumnumero = new javax.swing.JLabel();
        JLerro = new javax.swing.JLabel();
        JLacerto = new javax.swing.JLabel();
        TFrodada = new javax.swing.JTextField();
        TFtentativa = new javax.swing.JTextField();
        JLrodada = new javax.swing.JLabel();
        TFacerto = new javax.swing.JTextField();
        JLtentativa = new javax.swing.JLabel();
        TFerro = new javax.swing.JTextField();
        TFpainel = new javax.swing.JTextField();
        JBverificar = new javax.swing.JButton();
        JBreiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TFdigiteUmNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        JLdigiteumnumero.setText("    Digite um número");

        JLerro.setText("Erros");

        JLacerto.setText("Acertos");

        TFrodada.setEditable(false);
        TFrodada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFrodada.setText("0");

        TFtentativa.setEditable(false);
        TFtentativa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFtentativa.setText("0");

        JLrodada.setText("Rodada");

        TFacerto.setEditable(false);
        TFacerto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFacerto.setText("0");

        JLtentativa.setText("Tentativa(s)");

        TFerro.setEditable(false);
        TFerro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFerro.setText("0");

        TFpainel.setEditable(false);
        TFpainel.setText("Estou pensando em um número entre 0 e 50. adivinhe qual e.");

        JBverificar.setText("Verificar");
        JBverificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBverificarActionPerformed(evt);
            }
        });

        JBreiniciar.setText("Reiniciar");
        JBreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBreiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFpainel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLdigiteumnumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(JLtentativa)
                                    .addComponent(JLacerto)
                                    .addComponent(JLrodada)
                                    .addComponent(JLerro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TFacerto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, Short.MAX_VALUE)
                                        .addComponent(TFrodada, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(TFtentativa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFerro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TFdigiteUmNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBverificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBreiniciar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TFpainel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFdigiteUmNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLdigiteumnumero)
                    .addComponent(JBverificar)
                    .addComponent(JBreiniciar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFtentativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLtentativa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFacerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLacerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFerro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLerro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLrodada, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFrodada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBverificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBverificarActionPerformed

        vazio = "".equals(TFdigiteUmNumero.getText());
        if (vazio == false) {
            tentativa += 1;
            if (tentativa >= 5) {
                TFtentativa.setText(String.valueOf(tentativa));
                resposta = Integer.parseInt(TFdigiteUmNumero.getText());
                if (resposta == aleatorio) {
                    JOptionPane.showMessageDialog(null, "O número era mesmo o " + String.valueOf(resposta) + "\nAcertou na ultima tentativa!");
                    acerto();
                } else {
                    JOptionPane.showMessageDialog(null, "Perdeu ! O número era " + String.valueOf(aleatorio) + ".");
                    iniciar();
                }
            } else {
                TFtentativa.setText(String.valueOf(tentativa));
                resposta = Integer.parseInt(TFdigiteUmNumero.getText());
                if (resposta == aleatorio) {
                    JOptionPane.showMessageDialog(null, "Acertou !!!");
                    acerto();
                } else {
                    if (aleatorio > resposta) {
                        TFpainel.setText("Tente com um número maior");
                    } else {
                        TFpainel.setText("Tente com um número menor");
                    }
                    erro += 1;
                    TFerro.setText(String.valueOf(erro));
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite um número!");
        }
    }//GEN-LAST:event_JBverificarActionPerformed

    private void JBreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBreiniciarActionPerformed
        iniciar();
    }//GEN-LAST:event_JBreiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FramePrincipal().setVisible(true);
        });
    }

    public void iniciar() {

        aleatorio = pro.geraNumero();
        vazio = true;
        TFdigiteUmNumero.setText("");
        resposta = 0;
        acerto = 0;
        erro = 0;
        tentativa = 0;
        rodada = 0;
        TFacerto.setText("0");
        TFerro.setText("0");
        TFrodada.setText("0");
        TFtentativa.setText("0");
    }

    public void acerto() {
        acerto += 1;
        rodada += 1;
        tentativa = 0;
        TFacerto.setText(String.valueOf(acerto));
        TFrodada.setText(String.valueOf(rodada));
        TFtentativa.setText("0");
        aleatorio = pro.geraNumero();
        resposta = -1;
        TFdigiteUmNumero.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBreiniciar;
    private javax.swing.JButton JBverificar;
    private javax.swing.JLabel JLacerto;
    private javax.swing.JLabel JLdigiteumnumero;
    private javax.swing.JLabel JLerro;
    private javax.swing.JLabel JLrodada;
    private javax.swing.JLabel JLtentativa;
    public javax.swing.JTextField TFacerto;
    public javax.swing.JTextField TFdigiteUmNumero;
    public javax.swing.JTextField TFerro;
    private javax.swing.JTextField TFpainel;
    public javax.swing.JTextField TFrodada;
    public javax.swing.JTextField TFtentativa;
    // End of variables declaration//GEN-END:variables
}
